// بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيم
// This file is part of montrs.
// Copyright (C) 2026-Present Afsall Inc.
// SPDX-License-Identifier: Apache-2.0 OR MIT
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Alternatively, this file is available under the MIT License:
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

use leptos::prelude::*;
use montrs_icons::*;
use montrs_ui::prelude::*;

#[component]
pub fn AiKit() -> impl IntoView {
    let features = [
        (
            Glyph::Braces,
            "agent.json",
            "The project spec: plates, routes, tools, and package invariants \
             — machine-readable and always current.",
        ),
        (
            Glyph::Wrench,
            "@agent-tool",
            "Mark any function as agent-callable. Tools are curated into \
             tools.json automatically.",
        ),
        (
            Glyph::Blocks,
            "@agent-skill",
            "Composable, multi-step workflows defined as skills — fix an \
             error, add a feature, restructure.",
        ),
        (
            Glyph::FileSearch,
            "Error tracking",
            "Versioned error captures with suggested fixes and the exact code \
             context.",
        ),
        (
            Glyph::WandSparkles,
            "PRDoc",
            "Structured PR documentation validated and generated by the CLI.",
        ),
        (
            Glyph::Bot,
            "MCP server",
            "Expose the project to any MCP client: snapshots, errors, diffs, \
             and router structure.",
        ),
    ];

    view! {
        <div class="page-container py-12">
            <div class="mb-10">
                <h1 class="text-3xl font-bold tracking-tight">"AI Kit"</h1>
                <p class="mt-2 max-w-2xl text-muted-foreground">
                    "The agentic side of MontRS: your project is machine-readable
                    by design, so AI tools work on it without guessing."
                </p>
            </div>

            <div class="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
                {features.into_iter().map(|(icon, title, desc)| view! {
                    <div class="showcase-card reveal p-6">
                        <Icon glyph=icon class="h-6 w-6 text-primary" />
                        <h3 class="mt-4 font-semibold">{title}</h3>
                        <p class="mt-2 text-sm leading-6 text-muted-foreground">{desc}</p>
                    </div>
                }).collect::<Vec<_>>()}
            </div>

            <div class="mt-10 grid grid-cols-1 gap-8 lg:grid-cols-2">
                <div class="code-window">
                    <div class="code-window-bar">
                        <span class="traffic-light traffic-light-red"></span>
                        <span class="traffic-light traffic-light-yellow"></span>
                        <span class="traffic-light traffic-light-green"></span>
                        <span class="code-window-tab">"agent terminal"</span>
                    </div>
                    <pre class="code-window-body text-left">
                        <span class="terminal-prompt">"$"</span>
                        " montrs agent doctor"{"\n"}
                        <span class="token-string">"  ✅ root Cargo.toml found"</span>{"\n"}
                        <span class="token-string">"  ✅ .agent directory exists"</span>{"\n"}
                        <span class="token-string">"  ✅ all tracked errors resolved"</span>{"\n"}
                        <span class="token-string">"  ✅ rust toolchain available"</span>{"\n\n"}
                        <span class="terminal-prompt">"$"</span>
                        " montrs agent list-errors"{"\n"}
                        <span class="token-comment">"  # id  package  level  message"</span>{"\n"}
                        <span class="token-string">"  # 2/2 resolved · 0 pending"</span>
                    </pre>
                </div>
                <div class="flex flex-col justify-center space-y-4 text-sm text-muted-foreground">
                    <div class="flex items-center gap-3 rounded-md border border-border px-4 py-3">
                        <Icon glyph=Glyph::Cpu class="h-4 w-4 shrink-0 text-primary" />
                        "Skills: fixing-errors, adding-features, restructuring, new-projects"
                    </div>
                    <div class="flex items-center gap-3 rounded-md border border-border px-4 py-3">
                        <Icon glyph=Glyph::Server class="h-4 w-4 shrink-0 text-primary" />
                        "MCP: get_project_snapshot, agent_diff, agent_check, list_router_structure"
                    </div>
                    <div class="flex items-center gap-3 rounded-md border border-border px-4 py-3">
                        <Icon glyph=Glyph::Workflow class="h-4 w-4 shrink-0 text-primary" />
                        "Invariant checks surface exactly what you need — nothing more."
                    </div>
                </div>
            </div>
        </div>
    }
}
